# Generated by Django 5.2 on 2025-04-27 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the form', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the form', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the form was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the form was last updated')),
                ('created_by', models.ForeignKey(help_text='User who created the form', on_delete=django.db.models.deletion.CASCADE, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='User who last updated the form', on_delete=django.db.models.deletion.CASCADE, related_name='updated_forms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
