# Generated by Django 5.2 on 2025-04-27 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Name of the field', max_length=255)),
                ('field_mapping', models.CharField(choices=[('first_name', 'First Name'), ('last_name', 'Last Name'), ('phone', 'Phone'), ('email', 'Email'), ('address_line_1', 'Address Line 1'), ('address_line_2', 'Address Line 2'), ('city', 'City'), ('country', 'Country'), ('zip', 'ZIP/Postal Code'), ('message', 'Message')], help_text='Type of field (e.g., first_name, email, etc.)', max_length=50)),
                ('form', models.ForeignKey(help_text='The form this field belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='contact.form')),
            ],
        ),
    ]
