# Generated by Django 5.2 on 2025-04-27 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_formfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text='The submitted form data')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the submission was created')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the submitter', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the submitter', null=True)),
                ('form', models.ForeignKey(help_text='The form this submission belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contact.form')),
            ],
        ),
    ]
